exclude: '^docs/conf.py'

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
  - id: trailing-whitespace
    args: ['--markdown-linebreak-ext=md']
  - id: check-added-large-files
  - id: check-ast
  - id: check-case-conflict
  - id: check-json
  - id: check-merge-conflict
  - id: check-toml
  - id: check-xml
  - id: check-yaml
  - id: check-executables-have-shebangs
  - id: debug-statements
  - id: end-of-file-fixer
  - id: pretty-format-json
    args: ['--autofix', '--indent=4', '--no-sort-keys']
  - id: requirements-txt-fixer
  - id: mixed-line-ending
    args: ['--fix=auto']
  - id: no-commit-to-branch
    args: [--branch, main-priv, --branch, main]
- repo: https://github.com/psf/black
  rev: 22.3.0
  hooks:
  - id: black
    language_version: python3
- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
  - id: isort
- repo: https://github.com/PyCQA/flake8
  rev: 6.0.0
  hooks:
  - id: flake8
    args: [
        "--max-line-length=480",
        "--extend-ignore=E203,W503"
    ]
